import Link from 'next/link';
import './globals.css';
export const metadata = {
  title: 'Receita 19 - Next 4a',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  console.log("montando layout")
  return (
    <html lang="en">
      <body>
        <nav className="bg-light shadow-md">
          <div className="max-w-7xl mx-auto px-4 py-3">
            <Link href="/" className="text-xl font-semibold text-gray-800">
              Meu Site
            </Link>
            <button
              className="lg:hidden inline-flex items-center justify-center p-2 text-gray-500"
              type="button"
              aria-controls="navbarNav"
              aria-expanded="false"
              aria-label="Toggle navigation">
              <span className="block w-6 h-0.5 bg-gray-500"></span>
              <span className="block w-6 h-0.5 mt-1 bg-gray-500"></span>
            </button>
            <div className="lg:flex hidden justify-end space-x-4" id="navbarNav">
              <ul className="flex space-x-4">
                <li className="nav-item">
                  <Link href="/" className="text-gray-600 hover:text-gray-900">
                    Home
                  </Link>
                </li>
                <li className="nav-item">
                  <Link href="/movies" className="text-gray-600 hover:text-gray-900">
                    Movies
                  </Link>
                </li>
                <li className="nav-item">
                  <Link href="/clientMovies1" className="text-gray-600 hover:text-gray-900">
                   Client component com API
                  </Link>
                </li>
                <li className="nav-item">
                  <Link href="/movieBD" className="text-gray-600 hover:text-gray-900">
                   Movies com BD(Desafio)
                  </Link>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>

  )
}
